### ISSUE TITLE
Can you make the labels focusable?

### ISSUE THREAD

**Issue by aarongustafson** [EdwardBonnett/3dCssMaze#1]
I’m not sure if it’s possible to make it work via keyboard, but it’s currently not possible to move to the compass and play the game purely via the keyboard.

**Comment by EdwardBonnett** [comment]
I have now made these labels focusable, as well as the orbs. It's a good thought and got me thinking of how I could make this more accessible. I've now added a small amount of JavaScript specifically to aid accessibility for this reason. It will dynamically assign accesskeys to the labels as you move from room to room meaning the game can be played entirely via keyboard. 

I've now updated the submission. Is it possible to change the last line of the description on the project from "Absolutely no JavaScript is used and each level is less than 10kb in size." to "Absolutely no JavaScript is needed and each level is less than 10kb in size."?

Thanks
